#!/bin/bash

# set primary and seconday device
intern=$(xrandr -q |
        grep -wo ".* connected" |
        awk '{print $1}' |
        dmenu -p "Set primary monitor" -i -fn "Droid Sans Mono-9")
extern=$(xrandr -q |
        grep -wo ".* connected" |
        awk '{print $1}' |
        dmenu -p "Set secondary monitor" -i -fn "Droid Sans Mono-9")

curr_intern_res=$(xrandr -q|perl -F'\s|,' -lane "/^Sc/&&print join '',@F[8..10]")

# set the mode
MODE=$(echo -e "mirror\nonly-external\nonly-internal\nextended" |
        dmenu -p "Enter Mode: " -i -fn "Droid Sans Mono-9")

# if external monitor is going to be used ask for its resolution
if [[ $MODE == "mirror" || \
        $MODE == "only-external" || \
        $MODE == "extended" ]]
then
        CUSTOM_RES=$(echo -e "yes\nno" |
        dmenu -p "Set custom resolution?: " -i -fn "Droid Sans Mono-9")
        else
                CUSTOM_RES="no"
fi

# evaluate all the cases
case $CUSTOM_RES in
        yes)
                case $MODE in
                        mirror)
                                RES=$(xrandr -q |
                                        sed -n "/$extern/,/[A-Z]-[0-9]/p" |
                                        head -n -1 |
                                        tail -n +2 |
                                        awk '{print $1}' |
                                        dmenu -p "Select resolution: " -i -fn "Droid Sans Mono-9")
                                xrandr --output $extern --mode $RES --scale-from $curr_intern_res --output $intern --mode $curr_intern_res
                                ;;

                        only-external)
                                printf "Please specify custom resolution widthxheigth\n"
                                read RES
                                echo $RES
                                xrandr --output $intern --off --output $extern --mode $RES
                                ;;

                        extended)
                                printf "Please specify custom resolution widthxheigth\n"
                                read RES
                                echo $RES
                                xrandr --output $intern --auto --output $extern --right-of $intern --mode $RES
                                ;;

                        only-internal)
                                printf "Please specify custom resolution widthxheigth\n"
                                read RES
                                echo $RES
                                xrandr --output $extern --off --output $intern --mode $RES
                                ;;
                esac

                ;;

        no)
                case $MODE in
                        mirror)
                                xrandr --output $extern --auto --scale-from $curr_intern_res --output $extern --output $intern --mode $curr_intern_res
                                ;;

                        only-external)
                                xrandr --output $intern --off --output $extern --auto
                                ;;

                        extended)
                                xrandr --output $intern --auto --output $extern --right-of $intern --auto
                                ;;

                        only-internal)
                                xrandr --output $extern --off --output $intern --auto
                                ;;

                esac

                ;;
esac
