#!/bin/bash

# set primary and seconday device
intern=$(xrandr -q |
        grep -wo ".* connected" |
        awk '{print $1}' |
        dmenu -p "Set primary monitor")
extern=$(xrandr -q |
        grep -wo ".* connected" |
        awk '{print $1}' |
        dmenu -p "Set secondary monitor")

curr_intern_res=$(xrandr -q|perl -F'\s|,' -lane "/^Sc/&&print join '',@F[8..10]")

printf "external: $extern; internal: $intern\n"

printf "Enter Mode: mirror, only-external, only-internal, extended\n"
read MODE

printf "Set custom resolution for external monitor? (yes/no)\n"
read CUSTOM_RES

case $CUSTOM_RES in
        yes)
                case $MODE in
                        mirror)
                                printf "Please specify custom resolution widthxheigth\n"
                                read RES
                                echo $RES
                                xrandr --output $extern --mode $RES --scale-from $curr_intern_res --output $intern --mode $curr_intern_res
                                ;;

                        only-external)
                                printf "Please specify custom resolution widthxheigth\n"
                                read RES
                                echo $RES
                                xrandr --output $intern --off --output $extern --mode $RES
                                ;;

                        extended)
                                printf "Please specify custom resolution widthxheigth\n"
                                read RES
                                echo $RES
                                xrandr --output $intern --auto --output $extern --right-of $intern --mode $RES
                                ;;

                        only-internal)
                                printf "Please specify custom resolution widthxheigth\n"
                                read RES
                                echo $RES
                                xrandr --output $extern --off --output $intern --mode $RES
                                ;;
                esac

                ;;

        no)
                case $MODE in
                        mirror)
                                xrandr --output $extern --auto --scale-from $curr_intern_res --output $extern --output $intern --mode $curr_intern_res
                                ;;

                        only-external)
                                xrandr --output $intern --off --output $extern --auto
                                ;;

                        extended)
                                xrandr --output $intern --auto --output $extern --right-of $intern --auto
                                ;;

                        only-internal)
                                xrandr --output $extern --off --output $intern --auto
                                ;;

                esac

                ;;
esac
